name: Envoi de l'image sur DockerHub

on:
  workflow_dispatch:

jobs:
  build-et-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connexion à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et push de l'image Docker
        uses: docker/build-push-action@v6
        with:
          context: ./simple_api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-list:latest
